name: "Bug report"
description: "Something not working as expected? Tell us."
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
      placeholder: E.g., autoplay stops after one row when loop is on…
    validations:
      required: true
  - type: input
    id: repro
    attributes:
      label: Minimal reproduction
      placeholder: Steps or a sample CSV to reproduce
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: Browser + Version, OS, voice used
  - type: textarea
    id: logs
    attributes:
      label: Console output
      render: shell