name: "Feature request"
description: "Have an idea to make LingoFlow better?"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem/motivation
      placeholder: What are you trying to achieve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the feature and UI changes, if any.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered